let name="Siya George", roll=1001, maths=86, science=93, english=76, computer=88, social=82;
let total = maths + science + english + computer + social;
let average = total / 5;
let percent = average;
let grade;
if(average >= 90) grade = "A";
else if(average >= 80) grade = "B";
else if(average >= 70) grade = "C";
else if(average >= 60) grade = "D";
else grade = "F";
console.log("STUDENT RESULT REPORT");
console.log("Name:", name);
console.log("Roll No:", roll);
console.log("Maths:", maths);
console.log("Science:", science);
console.log("English:", english);
console.log("Computer:", computer);
console.log("Social:", social);
console.log("Total:", total);
console.log("Average:", average);
console.log("Percentage:", percent + "%");
console.log("Grade:", grade);